---

- import_tasks: install.deb.yml
  when: ansible_pkg_mgr == 'apt' and nodejs_install == 'pkg'

- import_tasks: install.yum.yml
  when: ansible_pkg_mgr == 'yum' and nodejs_install == 'pkg'

- import_tasks: install.src.yml
  when: nodejs_install == 'src'

- name: Install NPM modules
  npm: name={{item}} global=yes
  with_items: "{{nodejs_npm_modules}}"
